// ===== Sistema de Internacionalização (i18n) =====

class I18n {
    constructor() {
        this.translations = {
            pt: {
                'page-title': 'IniJS Wallpapers',
                'nav-gallery': 'Galeria',
                'nav-about': 'Sobre',
                'nav-contact': 'Contato',
                'hero-title': 'Wallpaper by IA Google AI Studio',
                'hero-subtitle': 'Wallpapers gerados por inteligência artificial, qualidade profissional',
                'gallery-title': 'Galeria de Wallpapers',
                'gallery-subtitle': 'Clique em qualquer imagem para visualizar em tela cheia',
                'gallery-click-msg': 'Clique para ampliar',
                'btn-download': 'Download',
                'btn-contact': 'Contatos',
                'about-title': 'Wallpaper by IA Google AI Studio',
                'about-text': 'Descubra uma coleção exclusiva de wallpapers gerados por inteligência artificial usando o Google AI Studio. Cada imagem é criada com algoritmos avançados de aprendizado de máquina, garantindo qualidade profissional e designs únicos. Perfeito para personalizar seu desktop e laptop.',
                'contact-title': 'Redes Sociais',
                'contact-subtitle': 'Tem alguma dúvida ou sugestão?',
                'btn-contacts': 'Contatos',
                'footer-copyright': '© 2025 Wallpaper by IA Google AI Studio. Todos os direitos reservados.',
                'footer-credits': 'Site gerado com Claude code | Copilot'
            },
            en: {
                'page-title': 'IniJS Wallpapers',
                'nav-gallery': 'Gallery',
                'nav-about': 'About',
                'nav-contact': 'Contact',
                'hero-title': 'Wallpaper by AI Google AI Studio',
                'hero-subtitle': 'Wallpapers generated by artificial intelligence, professional quality',
                'gallery-title': 'Wallpapers Gallery',
                'gallery-subtitle': 'Click any image to view it in full screen',
                'gallery-click-msg': 'Click to enlarge',
                'btn-download': 'Download',
                'btn-contact': 'Contacts',
                'about-title': 'Wallpaper by AI Google AI Studio',
                'about-text': 'Discover an exclusive collection of wallpapers generated by artificial intelligence using Google AI Studio. Each image is created with advanced machine learning algorithms, ensuring professional quality and unique designs. Perfect for personalizing your desktop and laptop.',
                'contact-title': 'Social Networks',
                'contact-subtitle': 'Have any questions or suggestions?',
                'btn-contacts': 'Contacts',
                'footer-copyright': '© 2025 Wallpaper by AI Google AI Studio. All rights reserved.',
                'footer-credits': 'Site generated with Claude code | Copilot'
            },
            es: {
                'page-title': 'IniJS Fondos de Pantalla',
                'nav-gallery': 'Galería',
                'nav-about': 'Acerca de',
                'nav-contact': 'Contacto',
                'hero-title': 'Fondos de pantalla por IA Google AI Studio',
                'hero-subtitle': 'Fondos de pantalla generados por inteligencia artificial, calidad profesional',
                'gallery-title': 'Galería de Fondos de Pantalla',
                'gallery-subtitle': 'Haz clic en cualquier imagen para verla a pantalla completa',
                'gallery-click-msg': 'Haz clic para ampliar',
                'btn-download': 'Descargar',
                'btn-contact': 'Contactos',
                'about-title': 'Fondos de pantalla por IA Google AI Studio',
                'about-text': 'Descubra una colección exclusiva de fondos de pantalla generados por inteligencia artificial usando Google AI Studio. Cada imagen se crea con algoritmos avanzados de aprendizaje automático, garantizando calidad profesional y diseños únicos. Perfecto para personalizar su escritorio y portátil.',
                'contact-title': 'Redes Sociales',
                'contact-subtitle': '¿Tienes alguna pregunta o sugerencia?',
                'btn-contacts': 'Contactos',
                'footer-copyright': '© 2025 Fondos de pantalla por IA Google AI Studio. Todos los derechos reservados.',
                'footer-credits': 'Sitio generado con Claude code | Copilot'
            },
            fr: {
                'page-title': 'IniJS Fonds d\'écran',
                'nav-gallery': 'Galerie',
                'nav-about': 'À propos',
                'nav-contact': 'Contact',
                'hero-title': 'Fond d\'écran par IA Google AI Studio',
                'hero-subtitle': 'Fonds d\'écran générés par l\'intelligence artificielle, qualité professionnelle',
                'gallery-title': 'Galerie de Fonds d\'écran',
                'gallery-subtitle': 'Cliquez sur n\'importe quelle image pour la voir en plein écran',
                'gallery-click-msg': 'Cliquez pour agrandir',
                'btn-download': 'Télécharger',
                'btn-contact': 'Contacts',
                'about-title': 'Fond d\'écran par IA Google AI Studio',
                'about-text': 'Découvrez une collection exclusive de fonds d\'écran générés par l\'intelligence artificielle à l\'aide de Google AI Studio. Chaque image est créée avec des algorithmes avancés d\'apprentissage automatique, garantissant une qualité professionnelle et des designs uniques. Parfait pour personnaliser votre bureau et votre ordinateur portable.',
                'contact-title': 'Réseaux Sociaux',
                'contact-subtitle': 'Vous avez une question ou une suggestion?',
                'btn-contacts': 'Contacts',
                'footer-copyright': '© 2025 Fond d\'écran par IA Google AI Studio. Tous droits réservés.',
                'footer-credits': 'Site généré avec Claude code | Copilot'
            },
            de: {
                'page-title': 'IniJS Hintergrundbilder',
                'nav-gallery': 'Galerie',
                'nav-about': 'Über',
                'nav-contact': 'Kontakt',
                'hero-title': 'Hintergrund von AI Google AI Studio',
                'hero-subtitle': 'Von künstlicher Intelligenz generierte Hintergrundbilder, professionelle Qualität',
                'gallery-title': 'Galerie mit Hintergrundbildern',
                'gallery-subtitle': 'Klicken Sie auf ein Bild, um es im Vollbildmodus anzuzeigen',
                'gallery-click-msg': 'Zum Vergrößern klicken',
                'btn-download': 'Herunterladen',
                'btn-contact': 'Kontakte',
                'about-title': 'Hintergrund von AI Google AI Studio',
                'about-text': 'Entdecken Sie eine exklusive Sammlung von Hintergrundbildern, die mit künstlicher Intelligenz mithilfe von Google AI Studio generiert wurden. Jedes Bild wird mit fortschrittlichen Algorithmen des maschinellen Lernens erstellt und garantiert professionelle Qualität und einzigartige Designs. Perfekt zur Personalisierung Ihres Desktops und Laptops.',
                'contact-title': 'Soziale Netzwerke',
                'contact-subtitle': 'Haben Sie eine Frage oder einen Vorschlag?',
                'btn-contacts': 'Kontakte',
                'footer-copyright': '© 2025 Hintergrund von AI Google AI Studio. Alle Rechte vorbehalten.',
                'footer-credits': 'Website generiert mit Claude code | Copilot'
            },
            it: {
                'page-title': 'IniJS Sfondi',
                'nav-gallery': 'Galleria',
                'nav-about': 'Chi Siamo',
                'nav-contact': 'Contatti',
                'hero-title': 'Sfondi di IA Google AI Studio',
                'hero-subtitle': 'Sfondi generati da intelligenza artificiale, qualità professionale',
                'gallery-title': 'Galleria Sfondi',
                'gallery-subtitle': 'Fai clic su qualsiasi immagine per visualizzarla a schermo intero',
                'gallery-click-msg': 'Fai clic per ingrandire',
                'btn-download': 'Scarica',
                'btn-contact': 'Contatti',
                'about-title': 'Sfondi di IA Google AI Studio',
                'about-text': 'Scopri una collezione esclusiva di sfondi generati da intelligenza artificiale utilizzando Google AI Studio. Ogni immagine è creata con algoritmi avanzati di apprendimento automatico, garantendo qualità professionale e design unici. Perfetto per personalizzare il tuo desktop e laptop.',
                'contact-title': 'Social Network',
                'contact-subtitle': 'Hai domande o suggerimenti?',
                'btn-contacts': 'Contatti',
                'footer-copyright': '© 2025 Sfondi di IA Google AI Studio. Tutti i diritti riservati.',
                'footer-credits': 'Sito generato con Claude code | Copilot'
            },
            ja: {
                'page-title': 'IniJSウォールペーパー',
                'nav-gallery': 'ギャラリー',
                'nav-about': '概要',
                'nav-contact': 'お問い合わせ',
                'hero-title': 'Google AI Studioによる壁紙',
                'hero-subtitle': '人工知能で生成されたウォールペーパー、プロフェッショナル品質',
                'gallery-title': 'ウォールペーパーギャラリー',
                'gallery-subtitle': '任意の画像をクリックしてフルスクリーンで表示します',
                'gallery-click-msg': 'クリックして拡大',
                'btn-download': 'ダウンロード',
                'btn-contact': 'お問い合わせ',
                'about-title': 'Google AI Studioによる壁紙',
                'about-text': 'Google AI Studioを使用した人工知能で生成されたウォールペーパーの限定コレクションをご覧ください。各イメージは高度な機械学習アルゴリズムで作成され、プロフェッショナル品質と独特なデザインを保証します。デスクトップとノートパソコンをパーソナライズするのに最適です。',
                'contact-title': 'ソーシャルネットワーク',
                'contact-subtitle': 'ご質問やご提案がありますか？',
                'btn-contacts': 'お問い合わせ',
                'footer-copyright': '© 2025 Google AI Studioによる壁紙。著作権所有。',
                'footer-credits': 'Claude code | Copilotで生成されたサイト'
            },
            zh: {
                'page-title': 'IniJS 壁纸',
                'nav-gallery': '图库',
                'nav-about': '关于',
                'nav-contact': '联系',
                'hero-title': '谷歌人工智能工作室壁纸',
                'hero-subtitle': '由人工智能生成的壁纸，专业质量',
                'gallery-title': '壁纸图库',
                'gallery-subtitle': '点击任何图像以全屏显示',
                'gallery-click-msg': '点击放大',
                'btn-download': '下载',
                'btn-contact': '联系',
                'about-title': '谷歌人工智能工作室壁纸',
                'about-text': '发现使用谷歌人工智能工作室生成的人工智能壁纸的独家集合。每张图像都是使用先进的机器学习算法创建的，保证专业质量和独特的设计。非常适合个性化您的桌面和笔记本电脑。',
                'contact-title': '社交网络',
                'contact-subtitle': '有任何问题或建议吗？',
                'btn-contacts': '联系',
                'footer-copyright': '© 2025 谷歌人工智能工作室壁纸。版权所有。',
                'footer-credits': '使用Claude code | Copilot生成的网站'
            }
        };

        this.currentLanguage = this.detectLanguage();
        this.init();
    }

    detectLanguage() {
        const browserLang = navigator.language || navigator.userLanguage;
        const langCode = browserLang.split('-')[0].toLowerCase();
        
        // Retornar idioma suportado ou português como padrão
        return this.translations[langCode] ? langCode : 'pt';
    }

    init() {
        document.documentElement.lang = this.currentLanguage;
        this.translatePage();
    }

    translatePage() {
        const elements = document.querySelectorAll('[data-i18n]');
        elements.forEach(element => {
            const key = element.getAttribute('data-i18n');
            const translation = this.translations[this.currentLanguage][key];
            
            if (translation) {
                // Para elementos de título e atributos
                if (element.tagName === 'TITLE') {
                    element.textContent = translation;
                } else {
                    element.textContent = translation;
                }
            }
        });
    }

    setLanguage(lang) {
        if (this.translations[lang]) {
            this.currentLanguage = lang;
            localStorage.setItem('preferred-language', lang);
            this.init();
        }
    }

    getLanguage() {
        return this.currentLanguage;
    }
}

// Inicializar i18n quando o DOM estiver pronto
document.addEventListener('DOMContentLoaded', () => {
    window.i18n = new I18n();
});
